service: inscricao-backend-lambda
frameworkVersion: '3'

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    fileName: requirements.txt

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  stage: dev

  environment:
    TELEGRAM_TOKEN: ${env:TELEGRAM_TOKEN}
    TELEGRAM_CHAT_ID: ${env:TELEGRAM_CHAT_ID}
    ASAAS: ${env:ASAAS}
    ADMIN_EMAIL: ${env:ADMIN_EMAIL}
    ADMIN_KEY: ${env:ADMIN_KEY}
    FIREBASE_BUCKET: ${env:FIREBASE_BUCKET}
    FIREBASE_KEY_PATH: ${env:FIREBASE_KEY_PATH}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:Scan
            - dynamodb:DeleteItem
          Resource: "*"
        - Effect: Allow
          Action:
          - s3:GetObject
          Resource: arn:aws:s3:::programaai-secrets/programaai-site-firebase-adminsdk-fbsvc-938d1ea4f3.json


functions:
  salvarInscricao:
    handler: handler.salvar_inscricao
    events:
      - http:
          path: '{proxy+}'
          method: any
          cors:
            origin: '*'
            headers:
              - Content-Type
              - Authorization
              - X-Amz-Date
              - X-Api-Key
              - X-Amz-Security-Token
            allowCredentials: false
