service: inscricao-backend-lambda
frameworkVersion: '3.38.0'

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  stage: dev

  environment:
    EMAIL_ORIGEM: ${env:EMAIL_ORIGEM}
    EMAIL_DESTINO: ${env:EMAIL_DESTINO}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - ses:SendEmail
          Resource: "*"

functions:
  salvarInscricao:
    handler: handler.salvar_inscricao
    events:
      - http:
          path: inscricao
          method: post
          cors: true

resources:
  Resources:
    Inscricoes:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Inscricoes
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
