service: inscricao-backend-lambda
frameworkVersion: '3'

plugins:
  - serverless-python-requirements

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  stage: dev

  environment:
    TELEGRAM_TOKEN: ${env:TELEGRAM_TOKEN}
    TELEGRAM_CHAT_ID: ${env:TELEGRAM_CHAT_ID}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
          Resource: "*"

functions:
  salvarInscricao:
    handler: handler.salvar_inscricao
    events:
      - http:
          path: inscricao
          method: post
          cors: true
