name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js (necessário para o Serverless Framework)
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Serverless Framework e Plugin
        run: |
          npm install -g serverless@3.38.0
          npm install --save-dev serverless-python-requirements

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set environment variables
        run: |
          echo "EMAIL_ORIGEM=${{ secrets.EMAIL_ORIGEM }}" >> $GITHUB_ENV
          echo "EMAIL_DESTINO=${{ secrets.EMAIL_DESTINO }}" >> $GITHUB_ENV
          echo "TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}" >> $GITHUB_ENV
          echo "TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }}" >> $GITHUB_ENV

      - name: Deploy with Serverless
        run: npx serverless deploy
